export const GET_TESTIMONIAL_BEGIN = 'GET_TESTIMONIAL_BEGIN';
export const GET_TESTIMONIAL_SUCCESS = 'GET_TESTIMONIAL_SUCCESS';
export const GET_TESTIMONIAL_FAILED = 'GET_TESTIMONIAL_FAILED';

export const GET_HELP_TIPS_BEGIN = 'GET_HELP_TIPSL_BEGIN';
export const GET_HELP_TIPS_SUCCESS = 'GET_HELP_TIPS_SUCCESS';
export const GET_HELP_TIPS_FAILED = 'GET_HELP_TIPSL_FAILED';
